replicaCount: 2
image:
  repository: hitfast/9000 # This is dockerhub repository name and image name It shouid understand from which repository it has to pull the image
  tag: latest # This is the tag of the image
  pullPolicy: IfNotPresent # This is the image pull policy first it will check the image locally if not present then it will pull from the repository
service:
  type: LoadBalancer # This is the service type
  port: 3000 # This is the port on which the service will be exposed
containerport: 9000 # This is the port on which the container is running inside the pod
appLabel: zomato # This is the label for the application

